---
- name: Filebeat Playbook
  hosts: webservers
  become: true
  tasks:
  - name: Download Filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
  - name: Install Filebeat deb
    command: sudo dpkg -i filebeat-7.6.1-amd64.deb
  - name: Copy Filebeat
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
  - name: Enable System Filebeat Modules
    command: sudo filebeat modules enable system
  - name: Filebeat Setup
    command: sudo filebeat setup
  - name: Service Filebeat Start
    command: sudo service filebeat start
  - name: Enable Filebeat Service on Boot
    systemd:
      name: filebeat
      enabled: yes