---
- name: Metricbeat Playbook
  hosts: webservers
  become: true
  tasks:
  - name: Download Metricbeat Deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
  - name: Install Metricbeat Deb
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb
  - name: Copy Metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
  - name: Enable Docker
    command: sudo metricbeat modules enable docker
  - name: Setup Metricbeat
    command: sudo metricbeat setup
  - name: Start Metricbeat Service
    command: sudo service metricbeat start
  - name: Enable Metricbeat on Boot
    systemd:
      name: metricbeat
      enabled: yes